### ISSUE TITLE
Authentication error from Instagram, should library automatically log user out?

### ISSUE THREAD

**Issue by adamjuhasz** [shyambhat/InstagramKit#110]
If the library detects that the user authentication has failed (change of password for example) an error is correctly passed up the chain. However, should it be the requestors responsibility to handle this, should instead the library log the user out automatically as the access token will never be valid again

**Comment by MarcGoVi** [comment]
@shyambhat What do you think about this first approximation? 885d106f6b3dfec867bfe98acfa8ccd4595536db
It exactly logs user out when the user's access token is no longer valid.

I can merge it to the dev branch if you like it.
