### ISSUE TITLE
Build issue when you include instagramKit.h

### ISSUE THREAD

**Issue by mkoosej** [shyambhat/InstagramKit#115]
I'm getting this error when I'm try to include instagramKit.h. 

``
libPods-voteStyle-InstagramKit.a(InstagramModel.o)
ld: 51 duplicate symbols for architecture arm64
``

There's something wrong with the model class that prevents building. The instagramEngine.h works if you include only this header file.

**Comment by mkoosej** [comment]
I commented line 22 to 83 of InstagramModel.m and it fixed it. What is the reason behind initializing those variables?

**Comment by shyambhat** [comment]
Merged PR #116. Thanks.
