### ISSUE TITLE
MinId pagination feature

### ISSUE THREAD

**Issue by romanvbabenko** [shyambhat/InstagramKit#119]
I'm a bit confused by the fact that all requests work only via max_id param.
It'd be great if the mix_id pagination is developed.
Fo instance, it'd be useful if you have stored in local cache media and want to fetch the new ones.

**Comment by shyambhat** [comment]
Please have a look at Instagram's API documentation to know what's possible and what's not.

**Comment by romanvbabenko** [comment]
Actually I did. Look, that was typo, I meant mix_id == min_id
Have a look https://instagram.com/developer/endpoints/users/ 
Almost all endpoints accept min_id parameter: MIN_ID	Return media later than this min_id
So I'm asking you apply this ability as max_id you've done.

**Comment by nicolasalliaume** [comment]
+1
