### ISSUE TITLE
Store access token using keychain but not NSUserDefaults

### ISSUE THREAD

**Issue by stefangeir** [shyambhat/InstagramKit#130]
An access token should rather be stored in the keychain than NSUserDefaults.

**Comment by shyambhat** [comment]
Correct. Will fix shortly.

**Comment by trauzti** [comment]
:+1:

**Comment by stefangeir** [comment]
:+1:

**Comment by techinpark** [comment]
good idea :+1:

**Comment by shyambhat** [comment]
Fixed in 3.6.6
https://github.com/shyambhat/InstagramKit/releases/tag/3.6.6
