### ISSUE TITLE
RedirectUrl can not be appName://

### ISSUE THREAD

**Issue by rayronvictor** [shyambhat/InstagramKit#131]
Since hostname is null, **appName://** does not seem to be a valid redirectUrl, as NULL isn't equals to NULL. I don't know if this is the expected behavior, but I would like to use appName:// as my redirectUrl. 

https://github.com/shyambhat/InstagramKit/blob/master/InstagramKit/Engine/InstagramEngine.m#L113

    NSURL *appRedirectURL = [NSURL URLWithString:self.appRedirectURL];
    
        if (![appRedirectURL.scheme isEqual:url.scheme] || ![appRedirectURL.host isEqual:url.host])
        {
            return NO;
        }
        ...
    }

**Comment by 99centbrains** [comment]
Did u setup a custom URLType in your app for this?

**Comment by shyambhat** [comment]
Fixed.
