### ISSUE TITLE
Relationship Endpoints

### ISSUE THREAD

**Issue by shyambhat** [shyambhat/InstagramKit#14]
http://instagram.com/developer/endpoints/relationships/

To contribute, please fork the branch 'relationships'

**Comment by driver733** [comment]
Is there any solution to this problem? I get the exact same error even for basic requests like "getSelfFeed"

**Comment by shyambhat** [comment]
@v0l0d you missed read Readme, maybe? 
For your app to POST or DELETE likes, comments or follows, you must apply to Instagram here : https://www.facebook.com/help/instagram/contact/185819881608116#
