### ISSUE TITLE
getuserfollowedbyuser give me same response for every call 

### ISSUE THREAD

**Issue by niaj-twinbit** [shyambhat/InstagramKit#143]
Hi,
I have called getuserfollowedbyuser to get the following list of a user but every time i call the api only give me same response and pagination isn't changing it's next url. i don't know  what is wrong.
please someone help.
thanks
Niaj

**Comment by nicolasalliaume** [comment]
Are you programming in swift?
I've discovered that InstagramPaginationInfo cannot be nil (I'd argue this) but the thing is that if you inspect at runtime, pagination info after fetching the last page is <uninitialized>. So what I've done to check if it's the last page is doing:

if nextPagination.nextURL.absoluteString != "" { /* has another page */ } else { /* this is last page */ }

Hope it helps!
Nico
