### ISSUE TITLE
Podfile

### ISSUE THREAD

**Issue by W2N-git** [shyambhat/InstagramKit#147]
If i try to install this Kit from pods, I get this message

[!] Unable to satisfy the following requirements:

- `InstagramKit/UICKeyChainStore (~> 2.0)` required by `Podfile`

**Comment by shyambhat** [comment]
Does your Podfile look like this? -
'''
pod 'InstagramKit', '~> 3.0'
pod 'InstagramKit/UICKeyChainStore', '~> 2.0'
'''

**Comment by glebus** [comment]
@shyambhat I just found the same issue. My Podfile:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'testProj' do

pod 'InstagramKit', '~> 3.0'
pod 'InstagramKit/UICKeyChainStore', '~> 2.0'

end

target 'testProjTests' do

end
```

Pod version 0.38.2

**Comment by shyambhat** [comment]
The culprit seems to be the ` '~> 2.0'` after `InstagramKit/UICKeyChainStore`.

Can you try with 
```
pod 'InstagramKit', '~> 3.0'
pod 'InstagramKit/UICKeyChainStore', '~> 2.0'
```
and let me know if it works? Will update the ReadMe if it does.

**Comment by glebus** [comment]
@shyambhat Yes! Your solution works for me. Thank you! 
And thank you for this great kit. It save a lot of time for me.

**Comment by shyambhat** [comment]
You're welcome :)
