### ISSUE TITLE
iOS 9 problem

### ISSUE THREAD

**Issue by AnaTP** [shyambhat/InstagramKit#157]
Hello everybody,

I'm having some issues with loading instagram info in iOS 9. It all works fine in iOS 7, but when I try to load instagram info in the view all the images all appear black and I have this message repeatedly: 

"NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)"

I tried to make an exception for instagram.com and to api.instagram.com but few things changed.

Does anyone has a clue of how to solve this?

Thanks in advance

**Comment by dezinezync** [comment]
@AnaTP This sounds like an App Transport Security Issue. Please refer to Apple's documentation on resolving the same: https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

Given that Instagram's API is 3rd party in this context, don't forget to use the keys marked with `NSThirdPartyException`.

Possible configuration that could work:

~~~~plist
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>instagram.com</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSThirdPartyExceptionMinimumTLSVersion</key>
            <string>TLSv1.0</string>
            <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
            <false/>
        </dict>
    </dict>
</dict>
~~~~

**Comment by AnaTP** [comment]
Thanks for your quick response and your help. I've already putted that exception tags. Still have the same problem. Any idea? If I discover the solution, I will post it here.

**Comment by dezinezync** [comment]
You try setting the `CFNETWORK_DIAGNOSTICS` preprocessor macro to a value between 1 (low logging) to 3(all outputs). This will log some more information which will help you debug better.

**Comment by AnaTP** [comment]
Hi. Thanks for your answer. 

I manage to solve this by using:

<key>instagram.com</key>
			<dict>
                    <key>NSIncludesSubdomains</key>
                    <true/>
                    <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                    <true/>
                    <key>NSTemporaryExceptionMinimumTLSVersion</key>
                    <string>TLSv1.0</string>
                    <key>NSRequiresCertificateTransparency</key>
                    <false/>
                    <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                    <true/>
                    <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                    <true/>
                    <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                    <string>TLSv1.0</string>
                    <key>NSExceptionAllowsInsecureHTTPLoads</key>
                    <true/>
			</dict>
            <key>scontent.cdninstagram.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSRequiresCertificateTransparency</key>
                <false/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <true/>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>

Hope this helps anyone.

Thanks again @dezinezync

**Comment by dezinezync** [comment]
Glad this got solved quickly.

**Comment by shyambhat** [comment]
Thanks guys. Reopening this for anyone who needs it.
