### ISSUE TITLE
`getSelfFeedWithSuccess:failure` always fails with 400 because count=0 is invalid

### ISSUE THREAD

**Issue by natan** [shyambhat/InstagramKit#165]
When you call `getSelfFeedWithSuccess:failure` it fails with:

```
{"meta":{"error_type":"APIInvalidParametersError","code":400,"error_message":"Count must be larger than zero."}}
```

Easy fix!

**Comment by shyambhat** [comment]
@natan This should fix it universally.

**Comment by natan** [comment]
@shyambhat Yep! LGTM.

**Comment by allsome** [comment]
hey,@shyambhat ,why I always receive failure with "Request failed: not found (404)" by the same function.

**Comment by allsome** [comment]
and the error code like this:"Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={NSUnderlyingError=0x127e60740 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html"

**Comment by allsome** [comment]
And the function "getPopularMediaWithSuccess" return the same error code almost,I can't find the target EndPoints in the official website,Is it still available or something I did wrong?

**Comment by shyambhat** [comment]
Hey @allsome, Instagram recently updated their platform and deprecated both these methods. 
You can find their update here -   http://developers.instagram.com/post/133424514006/instagram-platform-update. I'll have this info on the Readme going ahead.
