### ISSUE TITLE
It has no response at first time click login, and second time will show an error

### ISSUE THREAD

**Issue by alexliubj** [shyambhat/InstagramKit#168]
says: the page could not be loaded. if you have cookies disabled in your browser, or you are browsing in private mode, please try enabling cookies or turing off private mode, and then trying your action.

But actually I see my profile picture already, so not sure why like this. And I can also load my feed.. Btw the way at the beginning I have to click authorize for twice also not working properly.

Its' like this for both Simulator and Real device.

Any help would be appreciate.

**Comment by alexliubj** [comment]
never mind ,the view controller I thought should be closed right after...

**Comment by wxcoder** [comment]
Were you able to get rid of the error?
