### ISSUE TITLE
How to load user details of a media?

### ISSUE THREAD

**Issue by tdsolomons** [shyambhat/InstagramKit#180]
In earlier versions of InstagramKit, there was a method called loadUserDetails,
Now there is no such method.
and since user object in media is read only I cannot load the user separately and set it.

How do i do it?

**Comment by shyambhat** [comment]
Hi @tdsolomons, the method was renamed to ```getUserDetails: withSuccess: failure:```.
My apologies, this was long back when we weren't actively maintaining a change log. I'd recommend you switch to the latest version 3.6.9.

**Comment by tdsolomons** [comment]
Thanks.
And Is there a way to set InstagramMedia.user after loading the user details?
because I see that InstagramMedia.user is read only.

Yes I'm using latest version.

**Comment by tdsolomons** [comment]
<img width="759" alt="screen shot 2015-11-23 at 1 58 18 am" src="https://cloud.githubusercontent.com/assets/11621844/11326072/b8b564c0-9185-11e5-9027-9a0249f871dc.png">

here's the problem

**Comment by shyambhat** [comment]
I'm afraid that is not possible at the moment. We'd need to add a ```loadDetailsForUser:``` in the Engine which updates the same User object that it takes as input. Would appreciate if you can send a PR for that as you're already on it.
