### ISSUE TITLE
If I want to get more likes, which method should I use?

### ISSUE THREAD

**Issue by Shun87** [shyambhat/InstagramKit#181]
If I want to get more likes for a photo, what should I do? I saw that there are many apps in the app store had supported this feature.

**Comment by shyambhat** [comment]
You can use the pagination info object returned form the `getLikesOnMedia:` to make consequent paginated requests. Please look up details on the ReadMe or the [Pagination Wiki](https://github.com/shyambhat/InstagramKit/wiki/Pagination).
