### ISSUE TITLE
No possibility to retrieve Media id field

### ISSUE THREAD

**Issue by ricardopaiva** [shyambhat/InstagramKit#183]

**Comment by shyambhat** [comment]
The super class InstagramModel has an `Id` property.

**Comment by ricardopaiva** [comment]
Thanks for your reply! You're right.
I was having some kind of conflict with id attribute in another class...!
I've not checked the super class... I've looked only in InstagramMedia class. This is solved!

**Comment by shyambhat** [comment]
Awesome!
