### ISSUE TITLE
LikesCount and CommentCount returns wrong values

### ISSUE THREAD

**Issue by xinhuang327** [shyambhat/InstagramKit#193]
These two properties should be total likes/comments count, not loaded array's length. They were alright before adding users_in_photo features.

- (NSInteger)likesCount
{
    return [self.mLikes count];
}

- (NSInteger)commentCount
{
    return [self.mComments count];
}

**Comment by shyambhat** [comment]
Ah crap! Sorry for this. Will have it reverted soon. I'll appreciate it if you can submit a quick fix for this on the dev branch.

**Comment by shyambhat** [comment]
Fixed in v3.8.
