### ISSUE TITLE
New Permissions For Instagram

### ISSUE THREAD

**Issue by zzdjk6** [shyambhat/InstagramKit#194]
Since the Instagram announced new API usage policy, with new sandbox mode and new permissions.

refer here: https://www.instagram.com/developer/authorization/

public_content  and follower_list are new scope, I think there need change for this lib to adapt that:

1. add new constants in InstagramKitLoginScope
2. change stringForScope method

could I make a pull request?

**Comment by shyambhat** [comment]
Yes, please. On the dev branch. Thanks a bunch!

**Comment by ignacio-chiazzo** [comment]
@shyambhat @shyam-bhat  Take a look at this issue https://github.com/shyambhat/InstagramKit/issues/214, I think that the instagramKit is not storing the right access_token. The access_token doesn't have the follower_list scope, however I can see in the console that this permission is enable

**Comment by shyambhat** [comment]
@ignacio-chiazzo on it. Closing this issue for now.
