### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by wxcoder** [shyambhat/InstagramKit#195]
I downloaded the sample project, created a ```CFBundleURL``` scheme in my info.plist (e.g. "myurl://") which matches that in the instagram client, added the InstagramAppClientId and InstagramAppRedirectUR ("myurl://") and tried logging in. The login seems successful ( I can see my picture in the upper right corner) but I get an error saying: "This page could not be loaded. If you have cookies disabled in your browser, or you are browsing in Private Mode, please try enabling cookies or turning off Private Mode, and then retrying your action." It also seems the method ```- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType``` does not get called after having logged in, and the console also returns InstagramKit-Example[1901:616775] Load Popular Media Failed.

EDIT: It is entering  ```- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType``` but ```[[InstagramEngine sharedEngine] receivedValidAccessTokenFromURL:request.URL error:&error]``` never returns ```YES``` after logging in.

**Comment by wxcoder** [comment]
I solved this by reconfiguring my redirect uri.

**Comment by salmaanrizvi** [comment]
Hi, how did you reconfigure your redirect URI to work? I'm having the same issue.

Thanks!
