### ISSUE TITLE
Feed endpoint was changed to /media/recent

### ISSUE THREAD

**Issue by m1entus** [shyambhat/InstagramKit#206]
When i am trying to get @"users/self/feed" i am getting 404 error probably because of Instagram Sandbox, @"users/self/media/recent" this endpoint is working, could you add that ?

**Comment by shyambhat** [comment]
I'd appreciate a pull request. Thanks

**Comment by lorenzoPrimi** [comment]
+1 I'm having the same issue. 
Does it works with non-sandbox app?

**Comment by tne7laa** [comment]
+1 for me

**Comment by shyambhat** [comment]
This issue is being addressed in #221.
