### ISSUE TITLE
Unauthenticated requests going away completely?

### ISSUE THREAD

**Issue by StevenGurr** [shyambhat/InstagramKit#207]
I've only just spotted the changes to Instagram's API, coming this year. I think I've read and understood it all, but can anyone confirm that there will be no way at all to do unauthenticated requests to view and search without getting your app approved?

Rather frustratingly that is exactly the entire feature set that I want, as I've made a very cut down simple anonymous/private Instagram viewer, but it looks like my time is limited, as it looks like this doesn't meet their "valid use case" criteria. Can anyone confirm this is the case?

Thanks

**Comment by shyambhat** [comment]
@StevenGurr That's right. The API does not accept unauthenticated requests for Apps created on or after Nov 17th 2015.

The API changelog https://www.instagram.com/developer/changelog/ mentions `All API endpoints require a valid access_token`.
