### ISSUE TITLE
receivedValidAccessTokenFromURL return nothing in Swift framework

### ISSUE THREAD

**Issue by MaximeChaillou** [shyambhat/InstagramKit#212]
Hello,

I'm trying to convert the example from the readme, in Swift but I think there is a problem with the framework in Swift for the receivedValidAccessTokenFromURL function. The function should return a bool, but it returns nothing. Here the public function as I can see it : 
`public func receivedValidAccessTokenFromURL(url: NSURL) throws`
I guess it should be : 
`public func receivedValidAccessTokenFromURL(url: NSURL) throws -> Bool`

I use the last version of instagramKit (3.7) from Cocoapods.

Thank you

**Comment by MaximeChaillou** [comment]
The workaround I found for this : 
```
    func webView(webView: UIWebView, shouldStartLoadWithRequest request: NSURLRequest, navigationType: UIWebViewNavigationType) -> Bool{
        
        do {
            try InstagramEngine.sharedEngine().receivedValidAccessTokenFromURL(request.URL!)
            self.dismissViewControllerAnimated(true, completion: nil)
        }
        catch _ {
            print("No token found")
        }

        return true
    }
```

**Comment by MarcGoVi** [comment]
From Apple documentation:
> In Cocoa, methods that produce errors take an NSError pointer parameter as their last parameter, which populates its argument with an NSError object if an error occurs. Swift automatically translates Objective-C methods that produce errors into methods that throw an error according to Swift’s native error handling functionality.

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html

So by default this method in Swift is imported like this:
`func receivedValidAccessTokenFromURL(url: NSURL) throws`

As @MaximeChaillou said, we can handle the error like this:
```
do {
    try InstagramEngine.sharedEngine().receivedValidAccessTokenFromURL(request.URL!)
} catch let error as NSError {
    print("Error: \(error.localizedDescription)")
}
```

But there is a way to not throw an Error and keep the implementation code like in Objective-C. Adding the macro `NS_SWIFT_NOTHROW` to that declaration method, will prevent Swift to import it as a method that throws, allowing us to do:
```
var error:NSError?
if InstagramEngine.sharedEngine().receivedValidAccessTokenFromURL(request.URL, error: &error) {
    ....
} else {
    print("Error: \(error?.localizedDescription)")
}
```
And the method will be declared like this:
`func receivedValidAccessTokenFromURL(url: NSURL, error: NSErrorPointer) -> Bool`

@shyambhat If you agree with that solution I can make a PR to the dev branch.
Just let me know which solution you like more!

**Comment by MarcGoVi** [comment]
7256c3b5e65e8ed1525e5600366b20d62facfa9e

**Comment by ookerberry** [comment]
I'm running into this issue, too when using the 3.8 version of InstagramKit via cocoapods.  It would be great to have a fixed version available via cocoapods

**Comment by MarcGoVi** [comment]
Well it seems I had to send a PR directly instead of asking for opinion.
#227 
This issue can be closed.

**Comment by shyambhat** [comment]
Thanks @marcgovi
