### ISSUE TITLE
The scope  follower_list is not working

### ISSUE THREAD

**Issue by ignacio-chiazzo** [shyambhat/InstagramKit#214]
I am logged through instagramKit in my app, I am using the following four scopes :

`let scope: InstagramKitLoginScope = [InstagramKitLoginScope.Basic, InstagramKitLoginScope.Comments, InstagramKitLoginScope.Likes, InstagramKitLoginScope.Relationships]`

Note that I am using the Scope `InstagramKitLoginScope.Relationships`, and this is mapped with `follower_list scope`. I verified through the console and it seems like the four scopes are there.

However, When I send a request to get the relationship between two users I get the following error:

`NSErrorFaillingURLKey, Request failed: bad request (400)`

I copy the URL of the NSURL that I was using and looks like this : 

> https://api.instagram.com/v1/users/292******/relationship?access_token=********23.2972b4c.da*******

I put this URL on the Apigee console and tried to send a request and the server's response was :

>  "error_message": "This request requires scope=follower_list, but this access token is not authorized with this scope. The user must re-authorize your application with scope=follower_list to be granted this permissions."

Below here, I am gonna put the code that I am using to send the request:
```
        InstagramEngine.sharedEngine().getRelationshipStatusOfUser(userId, withSuccess: { (response) -> Void in
            print(response)
            success()
            }) { (errorM, errorInt) -> Void in
                _error()
        }
```

**Comment by ignacio-chiazzo** [comment]
@shyambhat  Did you find a solution for this issue?

**Comment by ignacio-chiazzo** [comment]
@natan @miukal @jacksonh @harrycheung

**Comment by uknowmeright** [comment]
This may be due to the follower_list requiring a different permission:

> 
follower_list - to read the list of followers and followed-by users
> 


try including:

InstagramKitLoginScope.FollowerList

hope this works!
