### ISSUE TITLE
LikesCount and CommentsCount to Zero in 3.7 version

### ISSUE THREAD

**Issue by geitoodevs** [shyambhat/InstagramKit#216]
You are expecting something like this in the response:

likes : { data : ....

And now is being received:

likes :  {
        count : 446
 }

So in this method is never entering:

self.mLikes = [[NSMutableArray alloc] init];
for (NSDictionary *userInfo in (info[kLikes])[kData]) {
            InstagramUser *user = [[InstagramUser alloc] initWithInfo:userInfo];
            [self.mLikes addObject:user];
}

And likes and comments always will be zero.

**Comment by geitoodevs** [comment]
Ok I've just seen that this only happens with sandbox mode!
Sorry, but I think it's good to know about this case.

Greetings.

**Comment by shyambhat** [comment]
Thanks for pointing out. This should be fixed in v3.8 in #203 and [this commit](https://github.com/shyambhat/InstagramKit/commit/8428cc764d12cfe3a167505837cacc982310d1ba).
