### ISSUE TITLE
Support for Instagram Platform updates

### ISSUE THREAD

**Issue by shyambhat** [shyambhat/InstagramKit#221]
Support API changes listed here : https://www.instagram.com/developer/changelog/
- Mark out deprecated methods.
- Use newer alternative methods.
- Document required scopes for each endpoint in comments.
- Remove request to Popular media from demo.
- Pop up login screen automatically on app start.

**Comment by nzackoya** [comment]
so what is fixed? I'm still having Not Found(404) when calling getFollowersOfUser

**Comment by TeamRainless** [comment]
@nzackoya Are you using the DEV branch?
