### ISSUE TITLE
ReceivedValidAccessTokenFromURL Error : "This operation could not be completed"

### ISSUE THREAD

**Issue by 1dividedby0** [shyambhat/InstagramKit#232]
My redirect URL is localhost:3000/auth/instagram/callback
This is my code:
`func webView(webView: UIWebView, shouldStartLoadWithRequest request: NSURLRequest, navigationType: UIWebViewNavigationType) -> Bool {

do{

try InstagramEngine.sharedEngine().receivedValidAccessTokenFromURL(request.URL!)

} catch let error as NSError {

  print("Error: (error.localizedDescription)")

}

 return true
    }`

**Comment by gugges** [comment]
The redirect URL you provided is not in the traditional http:// or appID:// URL format. Particularly, you are missing the http:// from the beginning of the URL.

I am pretty sure that's the root issue. If you breakpoint in the receivedValidAccessTokenFromURL you will see exactly where the check is failing on the callback.
