### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by antons81** [shyambhat/InstagramKit#241]
I have authenticated with my own account and got access token but when trying to fetch own feed getting error 404

 let engine = InstagramEngine.sharedEngine()
        engine.getSelfFeedWithSuccess({ (media, paginationInfo) in
            print(media)
            }) { (error, index) in
                print(error.localizedDescription)
                print(index)
        }

Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={NSUnderlyingError=0x7fdc4e9492d0 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fdc4e96c430> { URL: https://api.instagram.com/v1/users/self/feed?access_token=1223104.0e2b18e.c27e846d46f047bc8f999220779010f4 } { status code: 404, headers {
    "Cache-Control" = "private, no-cache, no-store, must-revalidate";
    "Content-Language" = en;
    "Content-Length" = 25232;
    "Content-Type" = "text/html";
    Date = "Sat, 25 Jun 2016 22:51:57 GMT";
    Expires = "Sat, 01 Jan 2000 00:00:00 GMT";
    Pragma = "no-cache";
    "Set-Cookie" = "csrftoken=QizHjwXQn3YCvyIH0TCtT7SgMG9uEFbM; expires=Sat, 24-Jun-2017 22:51:57 GMT; Max-Age=31449600; Path=/";
    Vary = "Cookie, Accept-Language";
    "x-frame-options" = SAMEORIGIN;
} }, NSErrorFailingURLKey=https://api.instagram.com/v1/users/self/feed?access_token=122310...

**Comment by gugges** [comment]
Instagram deprecated the /self/feed endpoint.

**Comment by kvnbautista** [comment]
@gugges what about instagram/tags/media/recent? is it deprecated as well?
![500x500bb](https://cloud.githubusercontent.com/assets/7776448/16363655/23fd86e8-3b97-11e6-9222-0386d3e37d30.jpg)

**Comment by mding5692** [comment]
I think get followers is deprecated as well, got the same error

**Comment by shyambhat** [comment]
The library has been updated to version 4.0 and the deprecated endpoints have been made unavailable.
