### ISSUE TITLE
getMediaForUser works only for the current authenticated instagram user

### ISSUE THREAD

**Issue by timaktimak** [shyambhat/InstagramKit#248]
I am trying to get images posted by a user by the user's instagram id. It works only if the user is my user, the one that has authenticated. Otherwise, it fails with bad request 400. Shouldn't I be able to get any user's instagram photos by their id (the ones with open accounts), not just the authenticated one's? This happens with both getMediaForUser methods, the one with pagination and without.

**Comment by jpmazza** [comment]
@timaktimak Both users must be sandbox users.

**Comment by shyambhat** [comment]
@timaktimak did you get around fixing this?
