### ISSUE TITLE
Error 403 in Sandbox (only get self)

### ISSUE THREAD

**Issue by ht22pt** [shyambhat/InstagramKit#253]
I try to use this library for my example app. It login ok, but when I test some API to get self information (getSelfFeedWithCount, getSelfUserDetailsWithSuccess, getSelfRecentMediaWithCount) and always return "Request failed: forbidden (403)".
- I check token OK.
  Can you give me some help?

**Comment by dirkmcpherson** [comment]
Check this out:
http://stackoverflow.com/questions/30322694/instagram-error-implicit-authentication-is-disabled

**Comment by shyambhat** [comment]
Thanks @dirkmcpherson
