### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by Gargo** [shyambhat/InstagramKit#275]
podspec has version 3.8, readme has version 3.0 - which one should I use?

**Comment by codelovin** [comment]
The latest is 3.8. There must be an error in the readme

**Comment by gerchicov-bp** [comment]
@codelovin it seems it should be mentioned without version

**Comment by leo150** [comment]
`~> 3.0` means all versions up to 4.0 (not including 4.0 and higher) so there is no error in readme.
