### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by Gargo** [shyambhat/InstagramKit#276]
getPopularMediaWithSuccess:failure: - broken method because it doesn't exist in instagram API now

**Comment by mding5692** [comment]
is getMediaForUser deprecated too? My apps have started to crash

**Comment by shyambhat** [comment]
Certain API endpoints, especially those that didn't require authentication (such as getPopularMedia) have been deprecated by Instagram a while ago. They have been made unavailable in InstagramKit 4.0.

Version 4.0 also fixes crashes around model objects. (#278)
