### ISSUE TITLE
Need fix InstagramUser.m

### ISSUE THREAD

**Issue by chepil** [shyambhat/InstagramKit#277]
//self.fullName = [[NSString alloc] initWithString:info[kFullName]]; //CRASH
    self.fullName =IKNotNull(info[kFullName]) ? [[NSString alloc] initWithString:info[kFullName]] : nil;

**Comment by shyambhat** [comment]
This issue is resolved. https://github.com/shyambhat/InstagramKit/pull/278
Thanks.
