### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by claytoncohn** [shyambhat/InstagramKit#45]
for some reason my likes stopped working today. no code changing or anything everything was working fine. I tested the demo and it had the same problem.

**Comment by rollinsw** [comment]
I'm having the same issue with this call. It seems to happen randomly and I am no where near the api rate limits. It happens maybe once out of every 20 calls to retrieve user details.

**Comment by claytoncohn** [comment]
It's not a matter of the API limit, Instagram has additional (undisclosed)
algorithms that prohibit certain functions depending on time, account, etc.

On Tue, Jan 13, 2015 at 9:19 AM, Bill Rollins <notifications@github.com>
wrote:

> I'm having the same issue with this call. It seems to happen randomly and
> I am no where near the api rate limits. It happens maybe once out of every
> 20 calls to retrieve user details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shyambhat/InstagramKit/issues/45#issuecomment-69759756>
> .
>



-- 

*Best Regards,*

Clayton

claytoncohn.me  <http://www.claytoncohn.me/>
@claytoncohn <http://www.twitter.com/claytoncohn>

**Comment by rollinsw** [comment]
After further testing, it's even more confusing. It seems to happen with certain users on certain days. On day 1, I will receive this error 100% of the time for user A. But I can still retrieve details for User B, User C and User D. On day 2, I will not receive the error for user A, but might receive it for User C 100% of the time.

I am making authenticated calls and am WAY below any rate limits. Really strange and I'd be willing to bet there is some problem with whatever algorithm Instagram is using for this.

Anyway, sorry to clutter up the issues for InstagramKit, this clearly is a problem on Instagram's side.

**Comment by rollinsw** [comment]
FYI, the issue has gone away for me. I have a feeling it is related to this: http://stackoverflow.com/questions/27915852/instagram-api-no-longer-grants-access-to-private-accounts
