### ISSUE TITLE
Signed calls

### ISSUE THREAD

**Issue by thedeveloper68** [shyambhat/InstagramKit#50]
Some new tools and rate limits have been introduced by instagram last month. If you find the time it would be great if you could implement the code for "signed" api calls, especially concerning POST methods for relationship endpoints (explained here: http://instagram.com/developer/restrict-api-requests/)

**Comment by amrittrivedir** [comment]
Hey i just modified the login flow to explicit and it works with sign headers for like and follow. Great library.
