### ISSUE TITLE
Allow Server Side authentication

### ISSUE THREAD

**Issue by shortstuffsushi** [shyambhat/InstagramKit#58]
Per Instagram's recommendations, it would be nice if this library provided a method to login with the `code` option instead of just always using `token`. The callback could expose this token, which the developer would then have to send to their server, and then eventually provide back to the InstagramKit engine.

Check out [their guide](http://instagram.com/developer/authentication/) for more information. It's not super vital, it would just be nice.

**Comment by shyambhat** [comment]
Sure. Feel free to fork the repo and include it if you have something working already.

**Comment by shyambhat** [comment]
Closing this issue as we've had no requests for this feature.
