### ISSUE TITLE
Login not working.

### ISSUE THREAD

**Issue by manishkungwani** [shyambhat/InstagramKit#66]
Hi,
I Installed IK as a cocoapod, and tried to implement login like in the demo, with a webview, but I get a compilation error, that IKLoginScope not found.
I tried the LoginWithBlock function as well, but that takes to the browser outside the application, and after logging in on the website, it takes me to the redirect uri, but does not return control to the application.

Please help.
Thanks
MK

**Comment by Raja413** [comment]
It shows me an error, code :403 and eeror type: Oauthforbiddenexception, error message: implicit authentication is disabled

**Comment by MPieter** [comment]
@Raja413 If you don't use a server component, you need to enable implicit authentication at the [Manage clients dashboard](https://instagram.com/developer/clients/manage/).

More information about this can be found at [https://instagram.com/developer/authentication/](https://instagram.com/developer/authentication/). In particular, the section about Client-Side (Implicit) Authentication.
