### ISSUE TITLE
Swift compiler error. Expected a type

### ISSUE THREAD

**Issue by puttputt** [shyambhat/InstagramKit#67]
Just trying to use InstagramKit in a swift project with a bridging header.

Theres a Swift Compiler Error in InstagramEngine.h on line 84. "Expected a Type"

- (bool)application:(UIApplication *)application
            openURL:(NSURL *)url
            sourceApplication:(NSString *)
            sourceApplication
            annotation:(id)annotation;

If I comment out that line, InstagramKit compiles and works.

**Comment by MPieter** [comment]
I had the same issues with the latest version (3.5.0).

Luckily the pull request fixes the problem, but it is a unfortunate that this fix is not yet released as a new version.

**Comment by shyambhat** [comment]
Fixed.
