### ISSUE TITLE
getFollowersOfUser returning 404

### ISSUE THREAD

**Issue by cytryn** [shyambhat/InstagramKit#70]
I dont know if the API changed but my attempts on getting the user followers returns 404.

Can you take a look?

Error getting Followers of user: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo=0x7f88e953a190 {NSUnderlyingError=0x7f88e9525600 "Request failed: unacceptable content-type: text/html", com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7f88e95288d0>

**Comment by cytryn** [comment]
any updates on this?

**Comment by SaurabhPrajapati** [comment]
i have same problem while frtching recent images.and it only occured first time.when i run the app again it works perfectly

**Comment by mmrmmlrr** [comment]
Having same issue for self feed request. Always fails

**Comment by cytryn** [comment]
@mmrmmlrr from my recent research on this I realized that instagram changed part of their api to private, so is no longer possible to publicly fetch these type of info anymore

**Comment by shyambhat** [comment]
Apologies for not getting back earlier @cytryn. This should be covered in #221.
