### ISSUE TITLE
Doesn't go for Auth after log out

### ISSUE THREAD

**Issue by RajChanchal** [shyambhat/InstagramKit#82]
Hi, why doesn't it go for Auth after log out? Is it a normal behavour or I am doing something wrong?
I call following code when logging out: [[InstagramEngine sharedEngine]logout];
And for log in, I use:
-(void)instagramLogin
{
self.scope = IKLoginScopeRelationships | IKLoginScopeComments | IKLoginScopeLikes;
NSDictionary *configuration = [InstagramEngine sharedEngineConfiguration];
NSString *scopeString = [InstagramEngine stringForScope:self.scope];
NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"%@?client_id=%@&redirect_uri=%@&response_type=token&scope=%@", configuration[kInstagramKitAuthorizationUrlConfigurationKey], configuration[kInstagramKitAppClientIdConfigurationKey], configuration[kInstagramKitAppRedirectUrlConfigurationKey], scopeString]];
[[UIApplication sharedApplication]openURL:url];
}
- (void)authenticateWithClientID:(NSString *)clientId callbackURL:(NSString *)callbackUrl {
  NSString *urlString = [NSString stringWithFormat:INSTAGRAM_AUTH_URL_FORMAT, clientId, callbackUrl];
  NSURL *url = [NSURL URLWithString:urlString];
  [[UIApplication sharedApplication] openURL:url];
}

**Comment by shyambhat** [comment]
fixed in v3.6.5
