### ISSUE TITLE
determining if instagramMedia was liked by self

### ISSUE THREAD

**Issue by hshafique** [shyambhat/InstagramKit#83]
Thanks for the great project. I have my own feed (using getSelfFeedWithCount) in an NSArray and I'm trying to determine if the media was liked by myself. The class InstagramMedia does not seem to have a property for liked by self. Do you know of any easy way to find this out?

Thanks

**Comment by supriyapathari** [comment]
Yes I am also facing same issue. I cannot like or comment. I alsways get failure message.
Please help.

**Comment by manumax** [comment]
@supriyapathari I think you're talking about a different problem. It seems more like you need to specify permission to add like or comment. Not sure I'm right but it is worth to give it a try. To do so you have to use `loginWithScope:completionBlock:` providing the proper scope (in your case `IKLoginScopeComments | IKLoginScopeLikes`).

**Comment by shyambhat** [comment]
@hshafique You can use the `userHasLiked` property in InstagramMedia.
http://cocoadocs.org/docsets/InstagramKit/3.6.5/Classes/InstagramMedia.html#//api/name/userHasLiked
