### ISSUE TITLE
wrong endpoints for Followed-By User

### ISSUE THREAD

**Issue by AndreFormSpicyApps** [shyambhat/InstagramKit#84]
Hello,

in the m file of InstaramEngine line 966 the method 

- (void)getUsersFollowedByUser:(NSString *)………

calls the endpoint :@"users/%@/follows"

I think it should call endpoint @"users/%@/followed-by"

Best Regards Andrew.

**Comment by jamonholmgren** [comment]
@AndreFormSpicyApps Actually, `users/%@/follows` is correct.

![endpoint api docs](http://clrsight.co/jh/2015-03-04-l9ndu.png?+)
