### ISSUE TITLE
Demo - No visible @interface for 'IKMediaViewController' declares the selector 'testLoadCounts'

### ISSUE THREAD

**Issue by hansaaaaa** [shyambhat/InstagramKit#94]
Hi,

I am trying to run the demo, but I get No visible @interface for 'IKMediaViewController' declares the selector 'testLoadCounts' on this code:

- (void)viewDidLoad
{
    [super viewDidLoad];

	// Do any additional setup after loading the view.

    self.title = [NSString stringWithFormat:@"@%@",self.media.user.username];

    [self testLoadCounts];
}

**Comment by ExoticObjects** [comment]
Same here. Would be nice if the demo worked!

**Comment by tdsolomons** [comment]
Same here. have anyone found an answer?

**Comment by manumax** [comment]
This should solve the problem. On commit 2e6b6849c5e2 method name ```testLoadCounts``` has been changed to ```loadUserDetails``` but was forgotten to reflect the change in the ```viewDidLoad``` method.

**Comment by ExoticObjects** [comment]
Actually, for anyone (like me!) who might just read these comments and not load the git diff, 'testLoadCounts' was renamed to 'testLoadUserDetails', not 'loadUserDetails'

**Comment by manumax** [comment]
Ops! Sorry, luckily the code is correct. Thank you!

**Comment by MPieter** [comment]
@shyambhat Could you please merge the pull request by @manumax ? 

I experienced the same issue when building the Demo project, and @manumax pull request fixes this.
